# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rCounter.proto\x12\rorg.m2sec.rpc\"%\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"s\n\x07Request\x12\x13\n\x0bhttpVersion\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12%\n\x06header\x18\x04 \x03(\x0b\x32\x15.org.m2sec.rpc.Header\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\"{\n\x08Response\x12\x13\n\x0bhttpVersion\x18\x01 \x01(\t\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12%\n\x06header\x18\x04 \x03(\x0b\x32\x15.org.m2sec.rpc.Header\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\x32\xe9\x03\n\x0e\x43ounterService\x12H\n\x16\x63ounterRequestToBeSent\x12\x16.org.m2sec.rpc.Request\x1a\x16.org.m2sec.rpc.Request\x12K\n\x17\x63ounterResponseReceived\x12\x17.org.m2sec.rpc.Response\x1a\x17.org.m2sec.rpc.Response\x12M\n\x1b\x63ounterProxyRequestReceived\x12\x16.org.m2sec.rpc.Request\x1a\x16.org.m2sec.rpc.Request\x12M\n\x1b\x63ounterProxyRequestToBeSent\x12\x16.org.m2sec.rpc.Request\x1a\x16.org.m2sec.rpc.Request\x12P\n\x1c\x63ounterProxyResponseReceived\x12\x17.org.m2sec.rpc.Response\x1a\x17.org.m2sec.rpc.Response\x12P\n\x1c\x63ounterProxyResponseToBeSent\x12\x17.org.m2sec.rpc.Response\x1a\x17.org.m2sec.rpc.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Counter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEADER']._serialized_start=32
  _globals['_HEADER']._serialized_end=69
  _globals['_REQUEST']._serialized_start=71
  _globals['_REQUEST']._serialized_end=186
  _globals['_RESPONSE']._serialized_start=188
  _globals['_RESPONSE']._serialized_end=311
  _globals['_COUNTERSERVICE']._serialized_start=314
  _globals['_COUNTERSERVICE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
