# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HttpHook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eHttpHook.proto\x12\rorg.m2sec.rpc\"$\n\x06Header\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xa1\x01\n\x07Request\x12\x0e\n\x06secure\x18\x01 \x01(\x08\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0e\n\x06method\x18\x05 \x01(\t\x12\x10\n\x08\x66ullPath\x18\x06 \x01(\t\x12&\n\x07headers\x18\x07 \x03(\x0b\x32\x15.org.m2sec.rpc.Header\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\x0c\"x\n\x08Response\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12&\n\x07headers\x18\x04 \x03(\x0b\x32\x15.org.m2sec.rpc.Header\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\x32\xaf\x02\n\x0fHttpHookService\x12\x43\n\x11hookRequestToBurp\x12\x16.org.m2sec.rpc.Request\x1a\x16.org.m2sec.rpc.Request\x12\x45\n\x13hookRequestToServer\x12\x16.org.m2sec.rpc.Request\x1a\x16.org.m2sec.rpc.Request\x12\x46\n\x12hookResponseToBurp\x12\x17.org.m2sec.rpc.Response\x1a\x17.org.m2sec.rpc.Response\x12H\n\x14hookResponseToClient\x12\x17.org.m2sec.rpc.Response\x1a\x17.org.m2sec.rpc.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HttpHook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEADER']._serialized_start=33
  _globals['_HEADER']._serialized_end=69
  _globals['_REQUEST']._serialized_start=72
  _globals['_REQUEST']._serialized_end=233
  _globals['_RESPONSE']._serialized_start=235
  _globals['_RESPONSE']._serialized_end=355
  _globals['_HTTPHOOKSERVICE']._serialized_start=358
  _globals['_HTTPHOOKSERVICE']._serialized_end=661
# @@protoc_insertion_point(module_scope)
